### GET request to example server
GET http://localhost:8080/products
#Authorization: Basic user 4f9462fb-c654-4d62-96c9-e14407819ec9
#Authorization: Basic admin 12345
Authorization: Basic user1 1234
#Authorization: Basic admin 1234
#Authorization: Basic dXNlcjE6MTIzNA==
#Authorization: Basic YWRtaW46MTIzNA==

###