### GET request to example server
GET http://localhost:8080/todos
#Authorization: Basic admin@miu.edu 12345
#Authorization: Basic user1@miu.edu 12345
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxLGFkbWluQG1pdS5lZHUsW2FkbWluXSIsImlhdCI6MTcyOTYzMTIxNCwiZXhwIjoxNzI5NjM0ODE0LCJpc3MiOiJNSVUifQ.XbkY4eL_YLlI-tXB33Nmx-l6lk1YzlAy9c6vRPJ8AEc

###
#GET http://localhost:8080/todos